export default function PdfPreview({ data }) {
  const { name, sku, category, price, manufacturer, model, description, dimensions, warranty, origin } = data

  return (
    <div className="bg-white shadow-lg w-full aspect-[1/1.41] p-lg flex flex-col text-left relative overflow-hidden">
      <div className="flex justify-between items-start border-b border-primary/20 pb-md mb-lg">
        <div className="text-primary font-display text-headline-md tracking-tighter">EMERALD</div>
        <div className="text-right">
          <div className="font-label-md text-[10px] text-outline">PRODUCT DATA SHEET</div>
          <div className="font-body-sm font-bold text-on-surface">{sku}</div>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-md mb-lg">
        <div className="space-y-sm">
          <h1 className="font-headline-lg text-primary leading-tight">{name}</h1>
          <p className="text-body-sm text-on-surface-variant leading-relaxed">{description}</p>
        </div>
        <div className="bg-surface-container h-48 rounded flex items-center justify-center border border-outline-variant/30">
          <img
            className="max-h-full max-w-full object-contain p-sm"
            alt="Product"
            src="https://lh3.googleusercontent.com/aida-public/AB6AXuB7sKOjzMNHZNMrtb9sd8owWt92wztTWo1UORMGI6uaH5Nyn_nep_jgKaWAPhfYQ01n_luBRMHOczJNzSUTJ9r11Q0IKWmmx8PuBkqDPXEzv4wX_e6GTSPDgQEWYlP0_0VoRZVycoy1w8hSF7nHtQYNbTV2gfsEztiEcGvHYInw3SQTFg5-9Nfy42xvBCcDVBPwAKy3X3ItoI86bL1EoQjLD_H3IKunc67G-vT0ex7BPe3warW21ZU8"
          />
        </div>
      </div>

      <div className="grid grid-cols-3 gap-sm mb-lg">
        <div className="bg-surface-container-low p-sm rounded border border-outline-variant/10">
          <div className="font-label-md text-[9px] text-outline">MANUFACTURER</div>
          <div className="font-body-sm font-bold">{manufacturer}</div>
        </div>
        <div className="bg-surface-container-low p-sm rounded border border-outline-variant/10">
          <div className="font-label-md text-[9px] text-outline">MODEL</div>
          <div className="font-body-sm font-bold">{model}</div>
        </div>
        <div className="bg-surface-container-low p-sm rounded border border-outline-variant/10">
          <div className="font-label-md text-[9px] text-outline">PRICE</div>
          <div className="font-body-sm font-bold text-secondary">{price}</div>
        </div>
      </div>

      <div className="border-t border-outline-variant/30 pt-md">
        <h4 className="font-label-md text-on-surface-variant mb-xs">TECHNICAL SPECIFICATIONS</h4>
        <div className="grid grid-cols-2 gap-x-md gap-y-xs text-[11px]">
          <div className="flex justify-between border-b border-outline-variant/10 py-1">
            <span className="text-outline">Dimensiones</span>
            <span className="font-bold text-right">{dimensions}</span>
          </div>
          <div className="flex justify-between border-b border-outline-variant/10 py-1">
            <span className="text-outline">Garantía</span>
            <span className="font-bold text-right">{warranty}</span>
          </div>
          <div className="flex justify-between border-b border-outline-variant/10 py-1">
            <span className="text-outline">Origen</span>
            <span className="font-bold text-right">{origin}</span>
          </div>
          <div className="flex justify-between border-b border-outline-variant/10 py-1">
            <span className="text-outline">Categoría</span>
            <span className="font-bold text-right">{category}</span>
          </div>
        </div>
      </div>

      <div className="mt-auto pt-lg flex items-center justify-between opacity-50 grayscale contrast-125">
        <div className="flex gap-sm h-6">
          <div className="w-12 h-6 bg-outline-variant/20 rounded" />
          <div className="w-12 h-6 bg-outline-variant/20 rounded" />
          <div className="w-12 h-6 bg-outline-variant/20 rounded" />
        </div>
        <div className="text-[9px] text-outline italic">
          Generated by Emerald Docs Premium PDF Engine
        </div>
      </div>
    </div>
  )
}
